# Generated by Django 4.1.5 on 2023-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('story', models.TextField(max_length=250)),
            ],
        ),
    ]
