# Generated by Django 4.1.5 on 2023-02-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_transport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='trip',
            name='companions',
            field=models.ManyToManyField(to='main_app.companion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date',
            field=models.DateField(verbose_name='Travel Date'),
        ),
    ]
